version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TOKEN=${TOKEN}
      - OWNER_ID=${OWNER_ID}
      - MESSAGE_DUMP=${MESSAGE_DUMP}
      - OWNER_USERNAME=${OWNER_USERNAME}
      - SUDO_USERS=${SUDO_USERS}
      - DEV_USERS=${DEV_USERS}
      - WHITELIST_USERS=${WHITELIST_USERS}
